version: "2.4"

services:
  app:
    build: .
    command: jupyter lab
    volumes:
      - ./:/app:cached
      - ./.jupyter:/root/.jupyter:cached
    environment:
      TZ: "Asia/Tokyo"
      # SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      LOG_CONF_PATH: /app/conf/${LOG_CONF_PATH}
      SENTENCE_PIECE_MODEL_PATH: /app/models/${SENTENCE_PIECE_MODEL_PATH}
      JUPYTER_PATH: /app
    ports:
      - ${JUPYTER_LAB_PORT}:8888
    stdin_open: true
    tty: true
  #   depends_on:
  #     db:
  #       condition: service_healthy
  # db:
  #   image: postgres:11-alpine
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   environment:
  #     TZ: "Asia/Tokyo"
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - ./postgres/data:/var/lib/postgresql/data/
  #     - ./postgres/init:/docker-entrypoint-initdb.d
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   stdin_open: true
